# SPDX-PackageName: finnix-mirrors-website
# SPDX-PackageSupplier: Ryan Finnie <ryan@finnie.org>
# SPDX-PackageDownloadLocation: https://forge.colobox.com/finnix/finnix-mirrors-website
# SPDX-FileCopyrightText: © 2020 Ryan Finnie <ryan@finnie.org>
# SPDX-License-Identifier: MPL-2.0
[project]
name = "finnix-mirrors"
authors = [
    {name = "Ryan Finnie", email = "ryan@finnie.org"},
]
description = "mirrors.finnix.org"
readme = "README.md"
requires-python = ">=3.12"
license = "MPL-2.0"
dependencies = [
    "Django",
    "django[argon2]",
    "django-xff",
    "requests",
    "python-dateutil",
    "geoip2",
    "geopy",
    "tzdata",
]
dynamic = ["version"]

[project.optional-dependencies]
gunicorn = ["gunicorn"]

[build-system]
requires = ["setuptools>=59.6.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = [
    "finnixmirrors",
    "finnixmirrors.migrations",
    "finnixmirrors.management.commands",
    "finnixmirrors.tests",
]

[tool.black]
line-length = 132
