# Generated by Django 3.2.8 on 2022-02-28 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finnixmirrors", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mirrorurl",
            name="head_allowed",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="mirrorurl",
            name="range_allowed",
            field=models.BooleanField(default=False),
        ),
    ]
